/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#1a1c1c",
        "on-primary-fixed-variant": "#544600",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "on-error-container": "#ffdad6",
        "primary": "#fff6df",
        "surface-container-high": "#2a2a2a",
        "surface-variant": "#353535",
        "on-secondary-container": "#85df72",
        "primary-fixed-dim": "#e9c400",
        "on-surface-variant": "#d0c6ab",
        "inverse-on-surface": "#313030",
        "surface-tint": "#e9c400",
        "inverse-surface": "#e5e2e1",
        "secondary-fixed": "#9df888",
        "on-primary-fixed": "#221b00",
        "secondary": "#82db6f",
        "on-error": "#690005",
        "secondary-fixed-dim": "#82db6f",
        "on-tertiary-container": "#5e5f60",
        "tertiary-fixed-dim": "#c6c6c7",
        "tertiary-container": "#d9dada",
        "surface-container-lowest": "#0e0e0e",
        "background": "#131313",
        "on-secondary": "#003a00",
        "tertiary": "#f6f6f6",
        "on-primary": "#3a3000",
        "on-secondary-fixed-variant": "#005300",
        "primary-container": "#ffd700",
        "outline": "#999077",
        "on-primary-container": "#705e00",
        "surface-container-low": "#1c1b1b",
        "surface": "#131313",
        "on-background": "#e5e2e1",
        "on-tertiary-fixed-variant": "#454747",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed": "#002200",
        "error-container": "#93000a",
        "secondary-container": "#006300",
        "outline-variant": "#4d4732",
        "tertiary-fixed": "#e2e2e2",
        "error": "#ffb4ab",
        "surface-container-highest": "#353535",
        "primary-fixed": "#ffe16d",
        "on-tertiary": "#2f3131",
        "surface-container": "#20201f",
        "inverse-primary": "#705d00"
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "caption": ["Manrope", "sans-serif"],
        "display-xl": ["Hanken Grotesk", "sans-serif"],
        "label-bold": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "38px", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "display-xl": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "700" }]
      },
      spacing: {
        "gutter": "24px",
        "section-padding-mobile": "64px",
        "section-padding-desktop": "120px",
        "container-max": "1280px",
        "base": "8px"
      }
    },
  },
  plugins: [],
}
